### ISSUE TITLE
Product Module | Add Product

### ISSUE THREAD

**Issue by msbAtGit** [fssa-batch3/sec_c_sec_c_saraswathi.kaliyappan__corejava_project_2#1]
- [x] Product Validator
- [x] Product Service
- [x] Product DAO
- [x] Product Model

**Comment by msbAtGit** [comment]
- [x] Check for Spelling Errors in the code
- [x] Add proper comments in the validator.

**Comment by saraswathi234** [comment]
i cleared errors and i wrote commands for everything .Can  you check that once again.

**Comment by saraswathi234** [comment]
If i have completde product dao and servicelayer sir, you can also check it one more time.

**Comment by saraswathi234** [comment]
i have completde product dao and servicelayer.so,i have close this issue.
